farmacia_index:
    pattern:  /categoria/new
    defaults: { _controller: FarmaciaBundle:Catfarma:catNew }

 #************** Categoria Imv ***************#

categoria_list:
    pattern:  /categoria/list
    defaults: { _controller: FarmaciaBundle:Catfarma:catList }
    
categoria_new:
    pattern:  /categoria/new
    defaults: { _controller: FarmaciaBundle:Catfarma:catNew }
    
categoria_save:
    pattern:  /categoria/save
    defaults: { _controller: FarmaciaBundle:Catfarma:catSave }

categoria_show:
    pattern:  /categoria/{catImv}/show
    defaults: { _controller: FarmaciaBundle:Catfarma:catShow }

categoria_edit:
    pattern:  /categoria/{catImv}/edit
    defaults: { _controller: FarmaciaBundle:Catfarma:catEdit }
    
categoria_update:
    pattern:  /categoria/{catImv}/update
    defaults: { _controller: FarmaciaBundle:Catfarma:catUpdate }
    
#************** Farmacia ***************#

farmacia_list:
    pattern:  /list
    defaults: { _controller: FarmaciaBundle:Catfarma:farmaciaList }
    
farmacia_new:
    pattern:  /new
    defaults: { _controller: FarmaciaBundle:Catfarma:farmaciaNew }
    
farmacia_save:
    pattern:  /save
    defaults: { _controller: FarmaciaBundle:Catfarma:farmaciaSave }

farmacia_show:
    pattern:  /{farmacia}/show
    defaults: { _controller: FarmaciaBundle:Catfarma:farmaciaShow }

farmacia_edit:
    pattern:  /{farmacia}/edit
    defaults: { _controller: FarmaciaBundle:Catfarma:farmaciaEdit }
    
farmacia_update:
    pattern:  /{farmacia}/update
    defaults: { _controller: FarmaciaBundle:Catfarma:farmaciaUpdate }
    
    
#************** Ingreso ***************#

ingreso_search:
    pattern:  /ingreso/search
    defaults: { _controller: FarmaciaBundle:Ingreso:search }

ingreso_list:
    pattern:  /ingreso/list
    defaults: { _controller: FarmaciaBundle:Ingreso:list }
    
ingreso_result:
    pattern:  /ingreso/result
    defaults: { _controller: FarmaciaBundle:Ingreso:result }    
    
ingreso_new:
    pattern:  /ingreso/new
    defaults: { _controller: FarmaciaBundle:Ingreso:new }
    
ingreso_save:
    pattern:  /ingreso/save
    defaults: { _controller: FarmaciaBundle:Ingreso:save }

ingreso_show:
    pattern:  /ingreso/{ingreso}/show
    defaults: { _controller: FarmaciaBundle:Ingreso:show }

ingreso_edit:
    pattern:  /ingreso/{ingreso}/edit
    defaults: { _controller: FarmaciaBundle:Ingreso:edit }
    
ingreso_update:
    pattern:  /ingreso/{ingreso}/update
    defaults: { _controller: FarmaciaBundle:Ingreso:update }    
    
#************** IMV ***************#    

imv_list:
    pattern:  /imv/list
    defaults: { _controller: FarmaciaBundle:Imv:list }

imv_search:
    pattern:  /imv/search
    defaults: { _controller: FarmaciaBundle:Imv:search }
    
imv_new:
    pattern:  /imv/new
    defaults: { _controller: FarmaciaBundle:Imv:new }
    
imv_save:
    pattern:  /imv/save
    defaults: { _controller: FarmaciaBundle:Imv:save }

imv_show:
    pattern:  /imv/{imv}/show
    defaults: { _controller: FarmaciaBundle:Imv:show }

imv_edit:
    pattern:  /imv/{imv}/edit
    defaults: { _controller: FarmaciaBundle:Imv:edit }
    
imv_update:
    pattern:  /imv/{imv}/update
    defaults: { _controller: FarmaciaBundle:Imv:update }
    

#************** Inventario ***************#

inventario_list:
    pattern:  /inventario/list
    defaults: { _controller: FarmaciaBundle:Inventario:list }

inventario_new:
    pattern:  /inventario/new/{ingreso}
    defaults: { _controller: FarmaciaBundle:Inventario:new }
    
inventario_save:
    pattern:  /inventario/save/{ingreso}
    defaults: { _controller: FarmaciaBundle:Inventario:save }

  
inventario_show:
    pattern:  /inventario/{inventario}/show
    defaults: { _controller: FarmaciaBundle:Inventario:show }
    
inventario_edit:
    pattern:  /inventario/{inventario}/edit
    defaults: { _controller: FarmaciaBundle:Inventario:edit }

inventario_update:
    pattern:  /inventario/{inventario}/update
    defaults: { _controller: FarmaciaBundle:Inventario:update }  
    
inventario_delete:
    pattern:  /inventario/{inventario}/delete
    defaults: { _controller: FarmaciaBundle:Inventario:delete }      

#************** Traslado ***************#    

traslado_search:
    pattern:  /traslado/search
    defaults: { _controller: FarmaciaBundle:Traslado:search } 

traslado_result:
    pattern:  /traslado/result
    defaults: { _controller: FarmaciaBundle:Traslado:result }
    
traslado_list:
    pattern:  /traslado/list
    defaults: { _controller: FarmaciaBundle:Traslado:list }
    
traslado_new:
    pattern:  /traslado/new
    defaults: { _controller: FarmaciaBundle:Traslado:new }
    
traslado_save:
    pattern:  /traslado/save
    defaults: { _controller: FarmaciaBundle:Traslado:save }

traslado_show:
    pattern:  /traslado/{traslado}/show
    defaults: { _controller: FarmaciaBundle:Traslado:show }

traslado_edit:
    pattern:  /traslado/{traslado}/edit
    defaults: { _controller: FarmaciaBundle:Traslado:edit }
    
traslado_update:
    pattern:  /traslado/{traslado}/update
    defaults: { _controller: FarmaciaBundle:Traslado:update }
    
    
#************** Devoluion ***************#   

devolucion_search:
    pattern:  /devolucion/search
    defaults: { _controller: FarmaciaBundle:Devolucion:search } 

devolucion_result:
    pattern:  /devolucion/result
    defaults: { _controller: FarmaciaBundle:Devolucion:result }    



devolucion_list:
    pattern:  /devolucion/list
    defaults: { _controller: FarmaciaBundle:Devolucion:list }
    
devolucion_new:
    pattern:  /devolucion/new
    defaults: { _controller: FarmaciaBundle:Devolucion:new }
    
devolucion_save:
    pattern:  /devolucion/save
    defaults: { _controller: FarmaciaBundle:Devolucion:save }

devolucion_show:
    pattern:  /devolucion/{devolucion}/show
    defaults: { _controller: FarmaciaBundle:Devolucion:show }

devolucion_edit:
    pattern:  /devolucion/{devolucion}/edit
    defaults: { _controller: FarmaciaBundle:Devolucion:edit }
    
devolucion_update:
    pattern:  /devolucion/{devolucion}/update
    defaults: { _controller: FarmaciaBundle:Devolucion:update }    
    
 #************** ImvPyp ***************#    

imvpyp_list:
    pattern:  /imvpyp/list
    defaults: { _controller: FarmaciaBundle:ImvPyp:list }
    
imvpyp_search:
    pattern:  /imvpyp/search
    defaults: { _controller: FarmaciaBundle:ImvPyp:search }    
    
imvpyp_new:
    pattern:  /imvpyp/new
    defaults: { _controller: FarmaciaBundle:ImvPyp:new }
    
imvpyp_save:
    pattern:  /imvpyp/save
    defaults: { _controller: FarmaciaBundle:ImvPyp:save }

imvpyp_show:
    pattern:  /imvpyp/{imvpyp}/show
    defaults: { _controller: FarmaciaBundle:ImvPyp:show }

imvpyp_edit:
    pattern:  /imvpyp/{imvpyp}/edit
    defaults: { _controller: FarmaciaBundle:ImvPyp:edit }
    
imvpyp_update:
    pattern:  /imvpyp/{imvpyp}/update
    defaults: { _controller: FarmaciaBundle:ImvPyp:update }
    
imvpyp_delete:
    pattern:  /imvpyp/{imvpyp}/delete
    defaults: { _controller: FarmaciaBundle:ImvPyp:delete }    
    

