<?php

namespace knx\HistoriaBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * HcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HcRepository extends EntityRepository {
	// Se consultan todas las historias clinicas del paciente por medio de su cedula ordenadas por fecha ASC
	public function findHistoriasPaciente($identifi, $tipoid) {
		$em = $this->getEntityManager();
		$dql = $em->createQuery(
							"SELECT
								hc
							 FROM
								HistoriaBundle:Hc hc
							 JOIN
								hc.factura f
							 JOIN
								f.paciente p
							 WHERE										
								p.identificacion = :id AND
								p.tipoId = :tipo
							 ORDER BY
								hc.fechaIngre DESC");

		$dql->setParameter('id', $identifi);
		$dql->setParameter('tipo', $tipoid);
		return $dql->getResult();
	}

	// listar los diagnosticos que se encuentran asociados a la historia
	public function findHcDx($historia) {
		$em = $this->getEntityManager();
		$dql = $em->createQuery(
							"SELECT
								c.id,c.nombre,c.codigo
							 FROM
								HistoriaBundle:HcDx hcdx
							 JOIN
								hcdx.cie c
							 WHERE
								hcdx.hc = :id 
							 ORDER BY
								c.nombre ASC");

		$dql->setParameter('id', $historia);
		return $dql->getResult();
	}

	// listar los examenes que se encuentran asociados a la historia
	public function findHcExamen($historia) {
		$em = $this->getEntityManager();
		$dql = $em->createQuery(
							"SELECT
								e.id,e.nombre,e.codigo,e.tipo,hcEx.resultado
							 FROM
								HistoriaBundle:HcExamen hcEx
							 JOIN
								hcEx.examen e
							 WHERE
								hcEx.hc = :id
							 ORDER BY
								e.nombre ASC");

		$dql->setParameter('id', $historia);
		return $dql->getResult();
	}

	// listar los medicamentos que se encuentran asociados a la historia
	public function findHcLabora($historia) {
		$em = $this->getEntityManager();
		$dql = $em->createQuery(
							"SELECT
								m.id,m.principioActivo,m.presentacion,m.concentracion,m.posologia,hcMe.estado
							 FROM
								HistoriaBundle:MedicamentoHistoria hcMe
							 JOIN
								hcMe.medicamento m
							 WHERE
								hcMe.hc = :id
							 ORDER BY
								m.principioActivo ASC");

		$dql->setParameter('id', $historia);
		return $dql->getResult();
	}
	
	// listar todas las historias que se encuentran en obsevacion o en internacion
	public function listHcUrgencias()
	{
		$em = $this->getEntityManager();
		$dql = $em->createQuery("SELECT 
									h
								 FROM 
									HistoriaBundle:Hc h
								 WHERE
									h.destino = 'observacion' or
									h.destino = 'internacion' 
								 ORDER BY
									h.updated DESC");
		return $dql->getResult();
	}
}
