<?php

namespace knx\HistoriaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HcRepository extends EntityRepository
{
}
