facturacion_index:
    pattern:  /inicio
    defaults: { _controller: FacturacionBundle:Default:inicio }

facturacion_consulta_new:
    pattern:  /consulta/new
    defaults: { _controller: FacturacionBundle:Factura:newConsulta }
    
facturacion_consulta_save:
    pattern:  /consulta/save
    defaults: { _controller: FacturacionBundle:Factura:saveConsulta }
    
facturacion_consulta_show:
    pattern:  /consulta/{factura}/show
    defaults: { _controller: FacturacionBundle:Factura:showConsulta }

facturacion_consulta_edit:
    pattern:  /consulta/{factura}/edit
    defaults: { _controller: FacturacionBundle:Factura:editConsulta }
    
facturacion_paciente_buscar:
    pattern:  /paciente/buscar
    defaults: { _controller: FacturacionBundle:Factura:jxBuscarPaciente }
    requirements:
        _method: POST
        
facturacion_cargo_save:
    pattern:  /cargo/save
    defaults: { _controller: FacturacionBundle:Factura:jxCargoSave }
    requirements:
        _method: POST
        
facturacion_fv_imprimir:
    pattern:  /fv/{factura}/imprimir
    defaults: { _controller: FacturacionBundle:Factura:imprimir }

        
#******************** FACTURA CARGO ***************************#

reporte_cargo_new:
    pattern:  /reporte/cargo/new
    defaults: { _controller: FacturacionBundle:FacturaCargo:informeCargo }
    
reporte_cargo_question:
    pattern:  /reporte/cargo/question
    defaults: { _controller: FacturacionBundle:FacturaCargo:questionTipoCargo }

