facturacion_index:
    pattern:  /hello/{name}
    defaults: { _controller: FacturacionBundle:Default:index }

facturacion_actividad_new:
    pattern:  /actividad/new
    defaults: { _controller: FacturacionBundle:Factura:newActividad }
    
facturacion_actividad_save:
    pattern:  /actividad/save
    defaults: { _controller: FacturacionBundle:Factura:saveActividad }
    
facturacion_actividad_edit:
    pattern:  /actividad/{factura}/edit
    defaults: { _controller: FacturacionBundle:Factura:editActividad }
    
facturacion_paciente_buscar:
    pattern:  /paciente/buscar
    defaults: { _controller: FacturacionBundle:Factura:ajaxBuscarPaciente }
    requirements:
        _method:  POST
        
#******************** FACTURA CARGO ***************************#

reporte_cargo_new:
    pattern:  /reporte/cargo/new
    defaults: { _controller: FacturacionBundle:FacturaCargo:informeCargo }
    
reporte_cargo_question:
    pattern:  /reporte/cargo/question
    defaults: { _controller: FacturacionBundle:FacturaCargo:questionTipoCargo }