facturacion_index:
    pattern:  /hello/{name}
    defaults: { _controller: FacturacionBundle:Default:index }

facturacion_consulta_new:
    pattern:  /consulta/new
    defaults: { _controller: FacturacionBundle:Factura:newConsulta }
    
facturacion_consulta_save:
    pattern:  /consulta/save
    defaults: { _controller: FacturacionBundle:Factura:saveConsulta }
    
facturacion_consulta_show:
    pattern:  /consulta/{factura}/show
    defaults: { _controller: FacturacionBundle:Factura:showConsulta }

facturacion_consulta_edit:
    pattern:  /consulta/{factura}/edit
    defaults: { _controller: FacturacionBundle:Factura:editConsulta }
    
facturacion_procedimiento_new:
    pattern:  /procedimiento/new
    defaults: { _controller: FacturacionBundle:Factura:newProcedimiento }
    
facturacion_procedimiento_save:
    pattern:  /procedimiento/save
    defaults: { _controller: FacturacionBundle:Factura:saveProcedimiento }
    
facturacion_procedimiento_show:
    pattern:  /procedimiento/{factura}/show
    defaults: { _controller: FacturacionBundle:Factura:showProcedimiento }

facturacion_procedimiento_edit:
    pattern:  /procedimiento/{factura}/edit
    defaults: { _controller: FacturacionBundle:Factura:editProcedimiento }
    
facturacion_insumo_new:
    pattern:  /insumo/new
    defaults: { _controller: FacturacionBundle:Factura:newInsumo }
    
facturacion_insumo_save:
    pattern:  /insumo/save
    defaults: { _controller: FacturacionBundle:Factura:saveInsumo }
    
facturacion_insumo_show:
    pattern:  /insumo/{factura}/show
    defaults: { _controller: FacturacionBundle:Factura:showInsumo }

facturacion_insumo_edit:
    pattern:  /insumo/{factura}/edit
    defaults: { _controller: FacturacionBundle:Factura:editInsumo }
    
facturacion_paciente_buscar:
    pattern:  /paciente/buscar
    defaults: { _controller: FacturacionBundle:Factura:jxBuscarPaciente }
    requirements:
        _method: POST
        
facturacion_cargo_save:
    pattern:  /cargo/save
    defaults: { _controller: FacturacionBundle:Factura:jxCargoSave }
    requirements:
        _method: POST
        
facturacion_fv_imprimir:
    pattern:  /fv/{factura}/imprimir
    defaults: { _controller: FacturacionBundle:Factura:imprimir }

        
#******************** FACTURA CARGO ***************************#

reporte_cargo_new:
    pattern:  /reporte/cargo/new
    defaults: { _controller: FacturacionBundle:FacturaCargo:informeCargo }
    
reporte_cargo_question:
    pattern:  /reporte/cargo/question
    defaults: { _controller: FacturacionBundle:FacturaCargo:questionTipoCargo }

