<?php

namespace knx\FacturacionBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * FacturaCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaCargoRepository extends EntityRepository 
{
	public function findInformeGeneral($dateStart,$dateEnd)
	{
		$em = $this->getEntityManager();		
		$dql = $em->createQuery("SELECT c.nombre AS cliente,
										ca.soat, ca.nombre AS cargo,
										COUNT(fc.factura) AS cantidad,
										fc.vrUnitario, SUM(fc.vrFacturado) AS total 
								 FROM FacturacionBundle:FacturaCargo fc 
									JOIN fc.factura f
									JOIN fc.cargo ca 
									JOIN f.cliente c
								 WHERE fc.created >= :dateStart
									AND fc.created <= :dateEnd 
								 GROUP BY fc.cargo, f.cliente ORDER BY c.nombre, ca.soat ASC");

		$dql->setParameter('dateStart', $dateStart);
		$dql->setParameter('dateEnd', $dateEnd);
		return $dql->getResult();	
	}
	
	public function findInformeRegimen($dateStart,$dateEnd)
	{
		$em = $this->getEntityManager();
		$dql = $em->createQuery("SELECT c.nombre AS cliente, c.tipo AS regimen,
										ca.soat, ca.nombre AS cargo,
										COUNT(fc.factura) AS cantidad,
										fc.vrUnitario, SUM(fc.vrFacturado) AS total
								 FROM FacturacionBundle:FacturaCargo fc
									JOIN fc.factura f
									JOIN fc.cargo ca
									JOIN f.cliente c
								 WHERE fc.created >= :dateStart
									AND fc.created <= :dateEnd
								 GROUP BY fc.cargo, f.cliente ORDER BY c.tipo, ca.soat ASC");
	
		$dql->setParameter('dateStart', $dateStart);
		$dql->setParameter('dateEnd', $dateEnd);
		return $dql->getResult();
	}

}
