usuario_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UsuarioBundle:Default:index }
    
usuario_list:
    pattern: /list
    defaults: { _controller: UsuarioBundle:Usuario:list }